CodebridgeTest/ViewModels/DogTableFilterViewModel.cs
using CodebridgeTest.Domain.Enums;
using CodebridgeTest.Helpers;
using System.ComponentModel.DataAnnotations;

namespace CodebridgeTest.ViewModels
{
    public class DogTableFilterViewModel
    {
        [Display(Name = "Field Name")]
        public DogFieldsName FieldName { get; set; }

        [Display(Name = "Sort Order")]
        public SortOrder SortOrder { get; set; }

        [Display(Name = "Page Size")]
        [Range(1, int.MaxValue, ErrorMessage = Consts.InvalidInteger)]
        public int PageSize { get; set; }

        [Display(Name = "Page Number")]
        [Range(1, int.MaxValue, ErrorMessage = Consts.InvalidInteger)]
        public int PageNumber { get; set; }

        // Default values
        public DogTableFilterViewModel()
        {
            FieldName = DogFieldsName.Name;
            SortOrder = SortOrder.Ascending;
            PageSize = 10;
            PageNumber = 1;
        }
    }
}

CodebridgeTest/ViewModels/DogTableViewModel.cs
namespace CodebridgeTest.ViewModels
{
    public class DogTableViewModel
    {
        public List<DogViewModel> DogsList { get; set; }
        public DogTableFilterViewModel Filter { get; set; }
        public int TotalDogsCount { get; set; }
    }
}

CodebridgeTest/ViewModels/DogViewModel.cs
using CodebridgeTest.Helpers;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CodebridgeTest.ViewModels
{
    public class DogViewModel
    {
        public int Id { get; set; }

        [Display(Name = "Name")]
        [Required(ErrorMessage = Consts.RequiredFiedError)]
        public string Name { get; set; }

        [Display(Name = "Color")]
        [Required(ErrorMessage = Consts.RequiredFiedError)]
        public string Color { get; set; }

        [Display(Name = "Tail Length")]
        [Required(ErrorMessage = Consts.RequiredFiedError)]
        [Range(0, 250, ErrorMessage = Consts.LengthError)]
        public int TailLength { get; set; }

        [Display(Name = "Weight")]
        [Required(ErrorMessage = Consts.RequiredFiedError)]
        [Range(0, 250, ErrorMessage = Consts.LengthError)]
        public int Weight { get; set; }
    }
}

CodebridgeTest/Controllers/DogsController.cs
using CodebridgeTest.Helpers;
using CodebridgeTest.Services.Interfaces;
using CodebridgeTest.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace CodebridgeTest.Controllers
{
    public class DogsController : Controller
    {
        private readonly IDogsService _dogService;
        public DogsController(IDogsService dogService)
        {
            _dogService = dogService;
        }

        public async Task<IActionResult> Index(DogTableFilterViewModel filter)
        {
            if(!ModelState.IsValid)
                return BadRequest(ModelState);

            var table = await _dogService.GetTable(filter);

            return View(table);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateAsync(DogViewModel dog)
        {
            if (!ModelState.IsValid)
                return View(dog);

            if (await _dogService.IsDogExist(dog.Name))
            {
                ModelState.AddModelError(nameof(dog.Name), Consts.DogAlreadyExist);
                return View(dog);
            }

            await _dogService.Create(dog);
            return RedirectToAction("Index");
        }
    }
}

CodebridgeTest/Controllers/HomeController.cs
using CodebridgeTest.Helpers;
using Microsoft.AspNetCore.Mvc;

namespace CodebridgeTest.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Ping()
        {
            return Ok(Consts.ApplicationVersion);
        }
    }
}

CodebridgeTest/Views/Dogs/Create.cshtml
@model CodebridgeTest.ViewModels.DogViewModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    Layout = "_Layout";
}

<h1>Create dog</h1>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-route="create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Color" class="control-label"></label>
                <input asp-for="Color" class="form-control" />
                <span asp-validation-for="Color" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TailLength" class="control-label"></label>
                <input asp-for="TailLength" class="form-control" />
                <span asp-validation-for="TailLength" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Weight" class="control-label"></label>
                <input asp-for="Weight" class="form-control" />
                <span asp-validation-for="Weight" class="text-danger"></span>
            </div>

            <div class="form-group submit-button">
                <input class="col-6 btn btn-primary" type="submit" value="Create" />
            </div>
        </form>
    </div>
</div>

CodebridgeTest/Views/Dogs/Index.cshtml
@model CodebridgeTest.ViewModels.DogTableViewModel
@using CodebridgeTest.Domain.Enums

@{
    Layout = "_Layout";
}

<h1>Dogs</h1>


<div class="mt-3">
    @using (Html.BeginForm("Index", "Dogs"))
    {
        <div class="row">
            <div class="col-3">
                <label class="control-label">Field Name</label>
                @Html.DropDownList("FieldName", @Html.GetEnumSelectList(typeof(DogFieldsName)), new {@class = "form-select"})
            </div>
            <div class="col-3">
                <label class="control-label">Sort Order</label>
                @Html.DropDownList("SortOrder", @Html.GetEnumSelectList(typeof(SortOrder)), new {@class = "form-select"})
            </div>
            <div class="col-3">
                <label class="control-label">Page Size</label>
                @Html.TextBox("PageSize","10", new { type="number", @class = "form-control", min=1 })
            </div>
            <div class="col-3">
                <label class="control-label">Page Number</label>
                @Html.TextBox("PageNumber","1", new { type="number", @class = "form-control", min=1 })
            </div>
        </div>

        <input class="btn btn-primary mt-2" type="submit" value="Filter" />
    }
</div>


<div class="mt-5">
    <p>Total count: @Model.TotalDogsCount</p>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Name</th>
                <th>Color</th>
                <th>Tail Length</th>
                <th>Weight</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.DogsList)
            {
                <tr>
                    <td>@item.Name</td>
                    <td>@item.Color</td>
                    <td>@item.TailLength</td>
                    <td>@item.Weight</td>
                </tr>
            }
        </tbody>
    </table>
</div>

CodebridgeTest/Views/Home/Index.cshtml
@{
    Layout = "_Layout";
}
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers


<h1>Welcome to the Codebridge test task!</h1>
<h3>Developed by Artem Hermaniuk</h3>


<div class="mt-5">
    <p>1. At first, here you can check the application. Let's try: </p>
    <button id="ping-btn" class="btn btn-primary">Ping</button>
</div>

<div class="mt-5">
    <p>2. Then you can look at the table of dogs: </p>
    <a class="btn btn-primary" asp-controller="Dogs" asp-action="Index">Dogs</a>
</div>

<div class="mt-5">
    <p>3. And also, you can create a dog! </p>
    <a class="btn btn-primary" asp-controller="Dogs" asp-action="Create">Create</a>
</div>


<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    $(function () {
        $('#ping-btn').click(function () {
            $.ajax({
                url: '/Home/Ping',
                type: 'GET',
                success: function (result) {
                    alert(result);
                }
            });
        });
    });
</script>

CodebridgeTest/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
    <head>
        <meta name="viewport" content="width=device-width" />
        <title>Codebridge Test</title>
        <link   href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" 
                rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" 
                crossorigin="anonymous">
        <link rel="stylesheet" href="~/css/main.css" asp-append-version="true" />
    </head>
    <body>
        <div class="row mt-5">
            <div class="col-3">
            </div>
            <div class="col-6">
                @RenderBody()
            </div>
            <div class="col-3">
            </div>
        </div>
    </body>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" 
        integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
        crossorigin="anonymous">
</script>

</html>